server:
  port: 8085
spring:
  application:
    name: gateway
  config:
    import: optional:nacos:${spring.application.name}.yaml # 使用optional前缀表示Nacos不可用时也不阻止启动
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848 # Nacos服务器地址
        group: DEFAULT_GROUP
        file-extension: yaml        # 配置文件格式，默认为 properties
      discovery:
        server-addr: 127.0.0.1:8848 # 服务发现地址
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: course-service
          uri: lb://course-service
          predicates:
            - Path=/course/**
        - id: instruction-service
          uri: lb://instruction-service
          predicates:
            - Path=/courseResource/**,/homework/**
        - id: statistic-service
          uri: lb://statistic-service
          predicates:
            - Path=/statistic/**
      filter:
        forwarded-headers:
          enabled: false   # 禁用 ForwardedHeadersFilter
          remove-non-proxy-headers:
            enabled: false    # 一并禁用其他头过滤器（可选）
    loadbalancer:
      nacos:
        enabled: true
      cache:
        enabled: false
    discovery:
      enabled: true
therogram:
  jwt:
    location: classpath:therogram.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  auth:
    excludePaths:
      - /user/create
      - /user/login