server:
  port: 8083
spring:
  application:
    name: instruction-service
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${therogram.db.host}:3306/instruction-service?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${therogram.db.pw}
  config:
    import: optional:nacos::${spring.application.name}.yaml # 使用optional前缀表示Nacos不可用时也不阻止启动
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848 # Nacos服务器地址
        group: DEFAULT_GROUP
        file-extension: yaml        # 配置文件格式，默认为 properties
      discovery:
        server-addr: 127.0.0.1:8848 # 服务发现地址
mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
logging:
  level:
    com.therogram: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"