server:
  port: 8084
spring:
  application:
    name: statistic-service
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${therogram.db.host}:3306/therogram_academy?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${therogram.db.pw}
  config:
    import: optional:nacos::${spring.application.name}.yaml # 使用optional前缀表示Nacos不可用时也不阻止启动
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848 # Nacos服务器地址
        group: DEFAULT_GROUP
        file-extension: yaml        # 配置文件格式，默认为 properties
      discovery:
        server-addr: 127.0.0.1:8848 # 服务发现地址
        username: nacos
        password: nacos
        server-config:
          nacos.core.auth.plugin.nacos.token.secret.key=VGhpc0lzTXlDdXN0b21TZWNyZXRLZXkwMTIzNDU2Nzg=
mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    map-underscore-to-camel-case: true # 自动下划线转驼峰
  mapper-locations: classpath:mapper/*.xml # 保留XML支持
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
logging:
  level:
    com.therogram: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"